# Generated by Django 5.2.1 on 2025-05-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prva_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todositems',
            old_name='complited',
            new_name='completed',
        ),
    ]
